version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    timezone: Europe/London
  open-pull-requests-limit: 1
  ignore:
  - dependency-name: twine
    versions:
    - 3.3.0
    - 3.4.0
  rebase-strategy: disabled
